-- WC Engine — Postgres schema (Supabase). Mirror of db/schema.sql for the hosted backend.
-- Differences from the SQLite schema:
--   * AUTOINCREMENT      -> GENERATED BY DEFAULT AS IDENTITY
--   * REAL               -> DOUBLE PRECISION
--   * datetime('now')    -> CURRENT_TIMESTAMP (timestamptz)
--   * no PRAGMA foreign_keys (Postgres enforces FKs natively)
-- lib/db.py reads timestamps back as ISO strings on both backends, so app code is parity.

CREATE TABLE IF NOT EXISTS teams (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  confederation TEXT NOT NULL,
  group_code    TEXT,
  created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_form (
  team_id    TEXT PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
  played     INTEGER NOT NULL,
  wins       INTEGER NOT NULL,
  draws      INTEGER NOT NULL,
  losses     INTEGER NOT NULL,
  gf         INTEGER NOT NULL,
  ga         INTEGER NOT NULL,
  pass_acc   DOUBLE PRECISION NOT NULL DEFAULT 80,
  pressing   DOUBLE PRECISION NOT NULL DEFAULT 6,
  sos        DOUBLE PRECISION NOT NULL,
  notes      TEXT,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
  id          TEXT PRIMARY KEY,
  stage       TEXT NOT NULL,
  group_code  TEXT,
  kickoff     TEXT,                              -- ISO date string, kept portable
  home_id     TEXT REFERENCES teams(id),
  away_id     TEXT REFERENCES teams(id),
  home_goals  INTEGER,
  away_goals  INTEGER,
  status      TEXT NOT NULL DEFAULT 'scheduled',
  source      TEXT,
  updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_params (
  version    INTEGER PRIMARY KEY,
  params     TEXT NOT NULL,
  brier      DOUBLE PRECISION,
  log_loss   DOUBLE PRECISION,
  note       TEXT,
  approved   INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS power_ratings (
  team_id        TEXT PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
  power          DOUBLE PRECISION NOT NULL,
  prior_power    DOUBLE PRECISION,
  wc_games       INTEGER DEFAULT 0,
  params_version INTEGER,
  computed_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS squad_status (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id          TEXT REFERENCES teams(id) ON DELETE CASCADE,
  player           TEXT NOT NULL,
  status           TEXT NOT NULL,
  importance       DOUBLE PRECISION,
  power_adjustment DOUBLE PRECISION DEFAULT 0,
  source           TEXT,
  reported_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_predictions (
  match_id   TEXT PRIMARY KEY REFERENCES matches(id) ON DELETE CASCADE,
  pred_home  INTEGER NOT NULL,
  pred_away  INTEGER NOT NULL,
  source     TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS predictions (
  match_id        TEXT PRIMARY KEY REFERENCES matches(id) ON DELETE CASCADE,
  win_home        DOUBLE PRECISION,
  draw            DOUBLE PRECISION,
  win_away        DOUBLE PRECISION,
  pred_home_goals DOUBLE PRECISION,
  pred_away_goals DOUBLE PRECISION,
  params_version  INTEGER,
  computed_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_runs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent      TEXT NOT NULL,
  action     TEXT NOT NULL,
  payload    TEXT,
  status     TEXT NOT NULL DEFAULT 'proposed',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_matches_status  ON matches(status);
CREATE INDEX IF NOT EXISTS idx_matches_kickoff ON matches(kickoff);
CREATE INDEX IF NOT EXISTS idx_agent_runs      ON agent_runs(agent, created_at DESC);
