"""One-time data migration: copy local wc.db (SQLite) into Postgres / Supabase.

Run AFTER setting DATABASE_URL (the Supabase pooler URL) in .env:

    python scripts/migrate_to_postgres.py

Creates the Postgres schema if needed, then copies every table in FK-safe order. Your
local wc.db is read-only here. Idempotent — re-running upserts the same rows — so it's safe
to run again after the local DB picks up more results.
"""
import os
import sys
import sqlite3
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config
import lib.db as db

# FK-safe order: parents before children.
TABLES = ["teams", "team_form", "matches", "model_params", "power_ratings",
          "squad_status", "predictions", "agent_runs"]
PK = {"teams": "id", "team_form": "team_id", "matches": "id", "model_params": "version",
      "power_ratings": "team_id", "squad_status": "id", "predictions": "match_id",
      "agent_runs": "id"}
IDENTITY = {"squad_status", "agent_runs"}  # GENERATED BY DEFAULT AS IDENTITY


def main():
    if not os.environ.get("DATABASE_URL"):
        raise SystemExit("Set DATABASE_URL (Supabase pooler) in .env first — it's empty.")

    src = sqlite3.connect(config.DB_PATH)
    src.row_factory = sqlite3.Row
    dst = db.connect()          # Postgres, because DATABASE_URL is set
    if dst.backend != "postgres":
        raise SystemExit("DATABASE_URL did not resolve to a Postgres backend.")
    db.init_db(dst)             # create tables if missing

    total = 0
    for t in TABLES:
        rows = src.execute(f"SELECT * FROM {t}").fetchall()
        if not rows:
            print(f"  {t:14s} 0")
            continue
        cols = list(rows[0].keys())
        collist = ",".join(cols)
        placeholders = ",".join(["%s"] * len(cols))
        updates = ",".join(f"{c}=EXCLUDED.{c}" for c in cols if c != PK[t])
        sql = (f"INSERT INTO {t}({collist}) VALUES({placeholders}) "
               f"ON CONFLICT({PK[t]}) DO UPDATE SET {updates}")
        cur = dst.raw.cursor()
        for r in rows:
            cur.execute(sql, tuple(r[c] for c in cols))
        cur.close()
        print(f"  {t:14s} {len(rows)}")
        total += len(rows)

    # Copied explicit ids into IDENTITY columns; advance the sequences so future
    # inserts don't collide.
    for t in IDENTITY:
        dst.raw.execute(
            f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), "
            f"COALESCE((SELECT MAX(id) FROM {t}), 1))")

    dst.commit()
    src.close()
    dst.close()
    print(f"Migrated {total} rows into Postgres. Verify, then point the app at DATABASE_URL.")


if __name__ == "__main__":
    main()
